version: '3.5'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      ETCD_DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    volumes:
      - etcd-data:/etcd-data
    ports:
      - "2379:2379"
    networks:
      - my_bridge_network

  minio:
    image: minio/minio:RELEASE.2021-08-17T20-53-08Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    networks:
      - my_bridge_network

  milvus:
    image: milvusdb/milvus:v2.0.0
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_USE_SSL: "false"
      DATA_PATH: /milvus-data
      LOGS_PATH: /milvus-logs
    volumes:
      - milvus-data:/milvus-data
      - milvus-logs:/milvus-logs
    ports:
      - "19530:19530"
    networks:
      - my_bridge_network

volumes:
  etcd-data:
  minio-data:
  milvus-data:
  milvus-logs:

networks:
  my_bridge_network:
    external: true
