apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-storage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: C:/Users/EDY/Downloads/file_browser  # 确保这是有效的路径
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:v2.31.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /srv
          name: file-storage
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: file-storage-pvc
