version: "3"
services:
  xxl-job-admin:
    restart: always
    # docker 镜像
    image: xuxueli/xxl-job-admin:2.4.0
    # 容器名称
    container_name: xxl-job-admin
    # volumes:
    #   # 日志目录映射到主机目录
    #   - ./data/logs:/data/applogs
    networks:
      - my_bridge_network
    ports:
      # 端口映射
      - "31009:31009"
    environment:
      # 设置启动参数
      # PARAMS: "--server.port=31009 --server.servlet.context-path=/xxl-job-admin --spring.datasource.url=jdbc:mysql://mysql-test:3306/xxl-job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true --spring.datasource.username=root --spring.datasource.password=123456 --spring.mail.username=xxx@qq.com --spring.mail.password=xxxx --xxl.job.accessToken=xxljob123456"
      PARAMS: "--server.port=31009  --xxl.job.accessToken=xxljob123456"
      # PARAMS: "--server.port=31009"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-test:3306/aikms?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "123456"
networks:
  my_bridge_network:
    external: true