xxl:
  job:
    admin:
      addresses: http://127.0.0.1:31009/xxl-job-admin
    executor:
      appname: "aikms-executor"
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
